# Trabajo Ev 1

## Leer DataSet

In [2]:
import pandas as pd
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [58]:
raw_df = pd.read_csv("retail_store_sales.csv")
df = raw_df # Duplicado del DataSet

In [59]:
df.head(5)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [14]:
df.shape

(12575, 11)

## Limpieza de | Price Per Unit |	Quantity | Total Spent (Busqueda de Nulos)

In [55]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [60]:
# En los siguientes 4 codigos se buscan patrones en los que no se pueden recuperar los valores de las columnas Price Per Unit	Quantity	Total Spent
# Esto debido a que no por ejemplo , no podemos sacar el total sin la cantidad ni el precio unitario
# Busqueda de si Precio, Cantidad, Total son Nulos
df.loc[
      df['Price Per Unit'].isnull() & df['Quantity'].isnull() & df['Total Spent'].isnull(),
      ['Price Per Unit', 'Quantity', 'Total Spent']
    ]

Empty DataFrame
Columns: [Price Per Unit, Quantity, Total Spent]
Index: []

In [63]:
# Busqueda de si Cantidad, Total son Nulos
numeros_no_recuperables = df.loc[
      df['Quantity'].isnull() & df['Total Spent'].isnull(),
      ['Price Per Unit', 'Quantity', 'Total Spent']
    ]
numeros_no_recuperables.shape

(604, 3)

In [35]:
# Busqueda de si Precio, Cantidad son Nulos
df.loc[
      df['Price Per Unit'].isnull() & df['Quantity'].isnull(),
      ['Price Per Unit', 'Quantity', 'Total Spent']
    ]

Empty DataFrame
Columns: [Price Per Unit, Quantity, Total Spent]
Index: []

In [43]:
# Busqueda de si Precio, Total son Nulos
df.loc[
      df['Price Per Unit'].isnull() & df['Total Spent'].isnull(),
      ['Price Per Unit', 'Quantity', 'Total Spent']
    ]

Empty DataFrame
Columns: [Price Per Unit, Quantity, Total Spent]
Index: []

In [65]:
# df.drop(numeros_no_recuperables.index, axis=0) # Se puede modificar la tabla de origen usando inplace=True, por el momento da una copia sin las filas borradas
# Por ahora a la tabla limpia se llama df_clean
df_clean = df.drop(numeros_no_recuperables.index, axis=0)
df_clean.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                 609
Price Per Unit       609
Quantity               0
Total Spent            0
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    3988
dtype: int64

## Limpieza de | Price Per Unit |	Quantity | Total Spent (Rellenar Nulos)