# Trabajo Ev 1

## a

In [13]:
import pandas as pd
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

df = pd.read_csv("retail_store_sales.csv")
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

## Fechas

In [3]:
# Copia por seguridad
df2 = df.copy()

In [4]:
# Nulos
nulos = df2['Transaction Date'].isnull().sum()
nulos

np.int64(0)

In [5]:
fecha_ant = df2['Transaction Date'].min()
fecha_rec = df2['Transaction Date'].max()

print(f"Fecha más antigua: {fecha_ant}")
print(f"Fecha más reciente: {fecha_rec}")

Fecha más antigua: 2022-01-01
Fecha más reciente: 2025-01-18

No hay necesidad de buscar outliers en las fechas, ya que estas son regulares y tampoco hay algún producto sin fecha de transacción.

In [12]:
# Fecha a Timestamp

df2['Timestamp'] = pd.to_datetime(df['Transaction Date']).astype('int64') // 10**9
df2['Timestamp']

0        1712534400
1        1690070400
2        1664928000
3        1651881600
4        1664668800
            ...
12570    1693699200
12571    1660262400
12572    1724457600
12573    1703894400
12574    1659744000
Name: Timestamp, Length: 12575, dtype: int64

In [15]:
# Transformación manual
df_manual = df2.copy()

mm_scaler = MinMaxScaler()
df_manual['Timestamp_Norm'] = mm_scaler.fit_transform(df_manual[['Timestamp']])

df_manual

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied,Timestamp,Timestamp_Norm
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,1712534400,0.743935
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,1690070400,0.510332
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,1664928000,0.248877
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,1651881600,0.113208
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,1664668800,0.246181
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN,1693699200,0.548068
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False,1660262400,0.200359
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN,1724457600,0.867925
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True,1703894400,0.654088
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN,1659744000,0.194969

In [21]:
# Transformación Profesional
preprocesador = ColumnTransformer(transformers=[
    ('num', StandardScaler(), ['Timestamp'])
])

pipeline_final = Pipeline(steps=[
    ('prep', preprocesador)
])

matriz = pipeline_final.fit_transform(df_manual)

print(matriz)

[[ 0.82982644]
 [ 0.03117865]
 [-0.86269252]
 ...
 [ 1.25372411]
 [ 0.52265421]
 [-1.04699586]]